import type {
  Category,
  InboxItem,
  Integration,
  LifeDocument,
  LifeEvent,
  NotificationSettings,
  Reminder,
  User,
} from "./types";

/**
 * Demo dataset. Replace with real API data once the backend exists.
 * A fixed "today" keeps the demo copy (days remaining, etc.) coherent and
 * avoids server/client hydration differences.
 */
export const DEMO_TODAY = "2026-08-18";

export const demoUser: User = {
  id: "user_demo",
  name: "Alex Johnson",
  email: "alex.johnson@example.com",
  avatar: null,
  plan: "free",
  createdAt: "2026-05-02",
};

export const categories: Category[] = [
  { id: "home", name: "Home", icon: "Home", description: "Your apartment, utilities and household paperwork." },
  { id: "car", name: "Car", icon: "Car", description: "Everything related to your vehicle." },
  { id: "money", name: "Money", icon: "Wallet", description: "Bills, statements and everyday finances." },
  { id: "purchases", name: "Purchases", icon: "ShoppingBag", description: "Receipts, orders and returns." },
  { id: "insurance", name: "Insurance", icon: "ShieldCheck", description: "Policies, renewals and coverage." },
  { id: "subscriptions", name: "Subscriptions", icon: "Repeat", description: "Recurring services and renewals." },
  { id: "contracts", name: "Contracts", icon: "FileSignature", description: "Agreements you've signed." },
  { id: "government", name: "Government", icon: "Landmark", description: "Official notices and paperwork." },
  { id: "other", name: "Other", icon: "Folder", description: "Everything that doesn't fit elsewhere." },
];

export const categoryItemCounts: Record<string, number> = {
  home: 12,
  car: 8,
  money: 17,
  purchases: 43,
  insurance: 9,
  subscriptions: 14,
  contracts: 7,
  government: 3,
  other: 18,
};

export const demoDocuments: LifeDocument[] = [
  {
    id: "doc_insurance_renewal",
    userId: "user_demo",
    title: "Car Insurance Renewal",
    type: "insurance",
    category: "car",
    company: "Example Insurance",
    source: "email",
    fileUrl: null,
    fileName: "Car Insurance Renewal.pdf",
    receivedAt: "2026-08-18",
    status: "needs_review",
    summary: "Your policy renews automatically at a higher premium.",
    meaning: "Your car insurance policy is scheduled to renew automatically.",
    whatChanged: {
      label: "Premium",
      previous: "$1,420",
      current: "$1,673",
      delta: "$253",
    },
    requiredAction: "Review your policy before September 10.",
    ifYouDoNothing: "Your policy will automatically renew at the new premium.",
  },
  {
    id: "doc_amazon_order",
    userId: "user_demo",
    title: "Headphones order confirmation",
    type: "receipt",
    category: "purchases",
    company: "Riverbend Marketplace",
    source: "email",
    fileUrl: null,
    fileName: "Order 114-2938471.pdf",
    receivedAt: "2026-07-21",
    status: "processed",
    summary: "Your return window closes on August 20, 2026.",
    meaning: "You bought a pair of headphones. Returns are accepted for 30 days.",
    requiredAction: "Decide whether to keep or return the headphones before August 20.",
    ifYouDoNothing: "The return window closes and the purchase becomes final.",
  },
  {
    id: "doc_electricity_bill",
    userId: "user_demo",
    title: "Electricity bill — August",
    type: "bill",
    category: "home",
    company: "Northline Energy",
    source: "email",
    fileUrl: null,
    fileName: "Northline August Statement.pdf",
    receivedAt: "2026-08-05",
    status: "processed",
    summary: "$124 due on August 19, 2026.",
    meaning: "Your monthly electricity statement is ready and payment is due soon.",
    whatChanged: { label: "Amount", previous: "$109", current: "$124", delta: "$15" },
    requiredAction: "Pay $124 by August 19.",
    ifYouDoNothing: "A late fee may be added to next month's statement.",
  },
  {
    id: "doc_apartment_lease",
    userId: "user_demo",
    title: "Apartment lease renewal notice",
    type: "contract",
    category: "home",
    company: "Maple Court Residences",
    source: "upload",
    fileUrl: null,
    fileName: "Lease Renewal Notice.pdf",
    receivedAt: "2026-08-12",
    status: "needs_review",
    summary: "You need to confirm your renewal decision by September 28, 2026.",
    meaning: "Your building is asking whether you intend to renew your lease.",
    whatChanged: { label: "Monthly rent", previous: "$1,950", current: "$2,040", delta: "$90" },
    requiredAction: "Tell the leasing office whether you're renewing before September 28.",
    ifYouDoNothing: "The lease converts to month-to-month at a higher rate.",
  },
  {
    id: "doc_laptop_warranty",
    userId: "user_demo",
    title: "Laptop extended warranty",
    type: "warranty",
    category: "purchases",
    company: "Corewave Electronics",
    source: "upload",
    fileUrl: null,
    fileName: "Warranty Certificate.pdf",
    receivedAt: "2026-03-14",
    status: "processed",
    summary: "Coverage ends March 14, 2027.",
    meaning: "Your laptop is covered for accidental damage and hardware faults until March 2027.",
    ifYouDoNothing: "Coverage simply expires on the end date.",
  },
  {
    id: "doc_streaming_subscription",
    userId: "user_demo",
    title: "Streaming plan renewal",
    type: "receipt",
    category: "subscriptions",
    company: "Lumen Stream",
    source: "email",
    fileUrl: null,
    fileName: "Lumen Stream Renewal.pdf",
    receivedAt: "2026-08-03",
    status: "processed",
    summary: "Renews September 3, 2026 at $17.99/month.",
    meaning: "Your annual streaming plan will renew automatically next month.",
    ifYouDoNothing: "You'll be charged $17.99 on September 3.",
  },
  {
    id: "doc_vehicle_registration",
    userId: "user_demo",
    title: "Vehicle registration",
    type: "government",
    category: "car",
    company: "State Department of Motor Vehicles",
    source: "upload",
    fileUrl: null,
    fileName: "Vehicle Registration.pdf",
    receivedAt: "2025-10-02",
    status: "processed",
    summary: "Expires October 2, 2026.",
    meaning: "Your vehicle registration must be renewed before it expires.",
    requiredAction: "Renew your registration before October 2.",
    ifYouDoNothing: "Driving with an expired registration can result in a fine.",
  },
  {
    id: "doc_insurance_policy",
    userId: "user_demo",
    title: "Car insurance policy",
    type: "insurance",
    category: "car",
    company: "Example Insurance",
    source: "upload",
    fileUrl: null,
    fileName: "Policy Document.pdf",
    receivedAt: "2025-09-14",
    status: "processed",
    summary: "Your current coverage details.",
    meaning: "This is the full policy wording for your current coverage year.",
  },
  {
    id: "doc_car_purchase_receipt",
    userId: "user_demo",
    title: "Car purchase receipt",
    type: "receipt",
    category: "car",
    company: "Halden Motors",
    source: "upload",
    fileUrl: null,
    fileName: "Purchase Receipt.pdf",
    receivedAt: "2024-06-11",
    status: "processed",
    summary: "Proof of purchase for your vehicle.",
    meaning: "Keep this for resale, insurance claims and warranty questions.",
  },
];

export const demoEvents: LifeEvent[] = [
  {
    id: "evt_insurance_renewal",
    documentId: "doc_insurance_renewal",
    userId: "user_demo",
    title: "Car insurance renewal",
    description: "Your premium increased from $1,420 to $1,673.",
    deadline: "2026-09-10",
    priority: "high",
    amount: 1673,
    previousAmount: 1420,
    status: "open",
    category: "car",
    sourceLabel: "Example Insurance email",
  },
  {
    id: "evt_amazon_return",
    documentId: "doc_amazon_order",
    userId: "user_demo",
    title: "Return headphones",
    description: "Your return window closes soon.",
    deadline: "2026-08-20",
    priority: "medium",
    amount: null,
    previousAmount: null,
    status: "open",
    category: "purchases",
    sourceLabel: "Riverbend receipt",
  },
  {
    id: "evt_lease_renewal",
    documentId: "doc_apartment_lease",
    userId: "user_demo",
    title: "Apartment lease renewal",
    description: "Your renewal decision is approaching.",
    deadline: "2026-09-28",
    priority: "medium",
    amount: 2040,
    previousAmount: 1950,
    status: "open",
    category: "home",
    sourceLabel: "Maple Court notice",
  },
  {
    id: "evt_electricity_bill",
    documentId: "doc_electricity_bill",
    userId: "user_demo",
    title: "Pay electricity bill",
    description: "Your August statement is due.",
    deadline: "2026-08-19",
    priority: "high",
    amount: 124,
    previousAmount: 109,
    status: "open",
    category: "home",
    sourceLabel: "Northline Energy",
  },
  {
    id: "evt_registration",
    documentId: "doc_vehicle_registration",
    userId: "user_demo",
    title: "Renew vehicle registration",
    description: "Your registration expires in the autumn.",
    deadline: "2026-10-02",
    priority: "low",
    amount: null,
    previousAmount: null,
    status: "open",
    category: "car",
    sourceLabel: "DMV notice",
  },
  {
    id: "evt_streaming_renewal",
    documentId: "doc_streaming_subscription",
    userId: "user_demo",
    title: "Streaming plan renews",
    description: "Lumen Stream renews at $17.99/month.",
    deadline: "2026-09-03",
    priority: "low",
    amount: 17.99,
    previousAmount: null,
    status: "open",
    category: "subscriptions",
    sourceLabel: "Lumen Stream email",
  },
  {
    id: "evt_warranty_expiry",
    documentId: "doc_laptop_warranty",
    userId: "user_demo",
    title: "Laptop warranty ends",
    description: "Coverage for your laptop expires.",
    deadline: "2027-03-14",
    priority: "low",
    amount: null,
    previousAmount: null,
    status: "open",
    category: "purchases",
    sourceLabel: "Corewave certificate",
  },
  {
    id: "evt_dental_claim",
    documentId: null,
    userId: "user_demo",
    title: "Submit dental claim",
    description: "You paid out of pocket and can claim it back.",
    deadline: "2026-07-30",
    priority: "medium",
    amount: 180,
    previousAmount: null,
    status: "handled",
    category: "insurance",
    sourceLabel: "Clinic receipt",
  },
  {
    id: "evt_internet_bill",
    documentId: null,
    userId: "user_demo",
    title: "Pay internet bill",
    description: "July statement paid.",
    deadline: "2026-07-14",
    priority: "low",
    amount: 65,
    previousAmount: null,
    status: "handled",
    category: "home",
    sourceLabel: "Fiberline",
  },
];

export const demoInbox: InboxItem[] = [
  {
    id: "inb_insurance",
    userId: "user_demo",
    title: "Your policy is renewing soon",
    source: "email",
    detected: "Insurance renewal",
    status: "needs_review",
    receivedAt: "2026-08-18",
    preview: "Example Insurance — your annual premium for the coming year is $1,673.",
    documentId: "doc_insurance_renewal",
  },
  {
    id: "inb_lease",
    userId: "user_demo",
    title: "Lease renewal notice",
    source: "upload",
    detected: "Contract renewal",
    status: "needs_review",
    receivedAt: "2026-08-12",
    preview: "Maple Court Residences — please confirm your intent to renew by September 28.",
    documentId: "doc_apartment_lease",
  },
  {
    id: "inb_amazon",
    userId: "user_demo",
    title: "Your order has shipped",
    source: "email",
    detected: "Purchase",
    status: "processed",
    receivedAt: "2026-07-21",
    preview: "Riverbend Marketplace — order 114-2938471, returns accepted until August 20.",
    documentId: "doc_amazon_order",
  },
  {
    id: "inb_electricity",
    userId: "user_demo",
    title: "August statement ready",
    source: "email",
    detected: "Bill",
    status: "processed",
    receivedAt: "2026-08-05",
    preview: "Northline Energy — $124 due August 19.",
    documentId: "doc_electricity_bill",
  },
  {
    id: "inb_newsletter",
    userId: "user_demo",
    title: "Weekly savings newsletter",
    source: "email",
    detected: "Marketing",
    status: "ignored",
    receivedAt: "2026-08-16",
    preview: "Northline Energy — tips for lowering your bill this summer.",
    documentId: null,
  },
];

export const demoReminders: Reminder[] = [
  {
    id: "rem_1",
    eventId: "evt_amazon_return",
    userId: "user_demo",
    reminderDate: "2026-08-19",
    channel: "email",
    status: "scheduled",
  },
];

export const defaultNotificationSettings: NotificationSettings = {
  emailReminders: true,
  browserNotifications: false,
  leadTimes: [
    { days: 1, enabled: true },
    { days: 3, enabled: true },
    { days: 7, enabled: false },
    { days: 30, enabled: false },
  ],
  priorityAlerts: "high_medium",
};

export const demoIntegrations: Integration[] = [
  {
    id: "gmail",
    name: "Gmail",
    description: "Automatically identify important administrative emails.",
    connected: false,
  },
  {
    id: "outlook",
    name: "Outlook",
    description: "Bring administrative mail from your Outlook account.",
    connected: false,
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Add Life Admin deadlines to your calendar.",
    connected: false,
  },
];

export const suggestedQuestions = [
  "When does my car insurance expire?",
  "What bills are due this month?",
  "Do I have any warranties expiring soon?",
  "How much did my insurance increase?",
  "Show me everything related to my apartment.",
  "What subscriptions renew next month?",
];
