/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppCategoriesIndexRouteImport } from './routes/app.categories.index'
import { Route as AppCategoriesCategoryRouteImport } from './routes/app.categories.$category'
import { Route as AppDocumentsIndexRouteImport } from './routes/app.documents.index'
import { Route as AppDocumentsIdRouteImport } from './routes/app.documents.$id'
import { Route as AppTasksIndexRouteImport } from './routes/app.tasks.index'
import { Route as AppTasksIdRouteImport } from './routes/app.tasks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesCategoryRoute = AppCategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/help': typeof AppHelpRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/categories/$category': typeof AppCategoriesCategoryRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/tasks/$id': typeof AppTasksIdRoute
  '/app/categories/': typeof AppCategoriesIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/help': typeof AppHelpRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/categories/$category': typeof AppCategoriesCategoryRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/tasks/$id': typeof AppTasksIdRoute
  '/app/categories': typeof AppCategoriesIndexRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/help': typeof AppHelpRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/categories/$category': typeof AppCategoriesCategoryRoute
  '/app/documents/$id': typeof AppDocumentsIdRoute
  '/app/tasks/$id': typeof AppTasksIdRoute
  '/app/categories/': typeof AppCategoriesIndexRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/billing'
    | '/app/calendar'
    | '/app/help'
    | '/app/inbox'
    | '/app/search'
    | '/app/settings'
    | '/app/'
    | '/app/categories/$category'
    | '/app/documents/$id'
    | '/app/tasks/$id'
    | '/app/categories/'
    | '/app/documents/'
    | '/app/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/billing'
    | '/app/calendar'
    | '/app/help'
    | '/app/inbox'
    | '/app/search'
    | '/app/settings'
    | '/app'
    | '/app/categories/$category'
    | '/app/documents/$id'
    | '/app/tasks/$id'
    | '/app/categories'
    | '/app/documents'
    | '/app/tasks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/billing'
    | '/app/calendar'
    | '/app/help'
    | '/app/inbox'
    | '/app/search'
    | '/app/settings'
    | '/app/'
    | '/app/categories/$category'
    | '/app/documents/$id'
    | '/app/tasks/$id'
    | '/app/categories/'
    | '/app/documents/'
    | '/app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/': {
      id: '/app/categories/'
      path: '/categories'
      fullPath: '/app/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/$category': {
      id: '/app/categories/$category'
      path: '/categories/$category'
      fullPath: '/app/categories/$category'
      preLoaderRoute: typeof AppCategoriesCategoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/$id': {
      id: '/app/documents/$id'
      path: '/documents/$id'
      fullPath: '/app/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/': {
      id: '/app/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$id': {
      id: '/app/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/app/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInboxRoute: typeof AppInboxRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCategoriesCategoryRoute: typeof AppCategoriesCategoryRoute
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
  AppTasksIdRoute: typeof AppTasksIdRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppHelpRoute: AppHelpRoute,
  AppInboxRoute: AppInboxRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCategoriesCategoryRoute: AppCategoriesCategoryRoute,
  AppDocumentsIdRoute: AppDocumentsIdRoute,
  AppTasksIdRoute: AppTasksIdRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
